const XLSX = require("xlsx");
const fs = require('fs');

const workbook = XLSX.readFile("DougScore.xlsx");
const sheet_name_list = workbook.SheetNames;
const sheet = workbook.Sheets[sheet_name_list[0]];
const newSheet = Object.assign({}, sheet);

for (const cell in sheet) {
  if (cell.startsWith("Q")) {
    let link = sheet[cell].f
      ?.split(",")[0]
      .replace('HYPERLINK("', "")
      .replace('"', "");
    if (!link) {
      link = sheet[cell].l?.Target;
    }

    if (!link) {
      link = "";
    }

    newSheet[cell] = { t: "s", v: link, r: `<t>${link}</t>`, h: link, w: link };
  } else {
    if (cell.startsWith("Q")) {
      console.log(cell);
    }

    newSheet[cell] = sheet[cell];
  }
}

const xlData = XLSX.utils.sheet_to_json(newSheet, { header: 1 });
const exportData = [];
xlData.forEach((r, i) => {
  if (i < 3 || !r.length) return;
  exportData.push({
    yr: r[0],   // Year
    mk: r[1],   // Make
    md: r[2],   // Model
    s: r[3],    // Speed
    a: r[4],    // Acceleration
    h: r[5],    // Handling
    ff: r[6],   // Fun Factor
    cf: r[7],   // Cool Factor
    tw: r[8],   // Total Weekend
    f: r[9],    // Features
    c: r[10],   // Comfort
    q: r[11],   // Quality
    p: r[12],   // Practicality
    v: r[13],   // Value
    td: r[14],  // Total Daily
    ds: r[15],  // Doug Score
    vl: r[16],  // Video Link
    fs: r[17],  // Filming State
    fc: r[18],  // Filming City
    vc: r[19],  // Vehicle Country
  });
});

const json = `// Generated by xlstojs/dougScoreToJson.js
export const dougScoreRaw = ${JSON.stringify(exportData)}`;

const filename = `${__dirname}/dougScoreRaw.ts`
console.log(`Writing file ${filename}`)
fs.writeFile(filename, json, 'utf8', () => {});
